# Generated by Django 4.2.10 on 2024-02-13 06:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('secret_token', models.CharField(default=account.models.generate_token, max_length=32)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
